version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mumulbo/mmb-ms-msa-playground:dev
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:8084"
    volumes:
      - /home/ec2-user/deploy/mmb-ms-msa-playground/logs:/app/logs
    networks:
      - external-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - external-net

volumes:
  mysql_data:

networks:
  external-net:
    external: true
    name: sample-network